In [1]:
import numpy as np

def generate_matrix(size, low=0, high=9):
    return np.random.randint(low, high + 1, (size, size))

np.random.seed(42)  # For reproducibility
A = generate_matrix(16)
B = generate_matrix(16)

print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)

Matrix A:
[[6 3 7 4 6 9 2 6 7 4 3 7 7 2 5 4]
 [1 7 5 1 4 0 9 5 8 0 9 2 6 3 8 2]
 [4 2 6 4 8 6 1 3 8 1 9 8 9 4 1 3]
 [6 7 2 0 3 1 7 3 1 5 5 9 3 5 1 9]
 [1 9 3 7 6 8 7 4 1 4 7 9 8 8 0 8]
 [6 8 7 0 7 7 2 0 7 2 2 0 4 9 6 9]
 [8 6 8 7 1 0 6 6 7 4 2 7 5 2 0 2]
 [4 2 0 4 9 6 6 8 9 9 2 6 0 3 3 4]
 [6 6 3 6 2 5 1 9 8 4 5 3 9 6 8 6]
 [0 0 8 8 3 8 2 6 5 7 8 4 0 2 9 7]
 [5 7 8 3 0 0 9 3 6 1 2 0 4 0 7 0]
 [0 1 1 5 6 4 0 0 2 1 4 9 5 6 3 6]
 [7 0 5 7 4 3 1 5 5 0 8 5 2 3 3 2]
 [9 2 2 3 6 3 8 0 7 6 1 7 0 8 8 1]
 [6 9 2 6 9 8 3 0 1 0 4 4 6 8 8 2]
 [2 2 3 7 5 7 0 7 3 0 7 3 5 7 3 2]]

Matrix B:
[[8 2 8 1 1 1 5 2 8 3 0 3 0 4 3 7]
 [7 6 2 0 0 2 5 6 5 5 5 2 5 7 1 4]
 [0 0 4 2 3 2 0 0 4 5 2 8 4 7 0 4]
 [2 0 3 4 6 0 2 1 8 9 5 9 2 7 7 1]
 [5 6 1 9 1 9 0 7 0 8 5 6 9 6 9 2]
 [1 8 7 9 6 8 3 3 0 7 2 6 1 1 6 5]
 [2 8 9 5 9 9 5 0 3 9 5 5 4 0 7 4]
 [4 6 3 5 3 2 6 7 3 1 9 2 0 7 2 9]
 [6 9 4 9 4 6 8 4 0 9 9 0 1 5 8 7]
 [4 0 6 4 5 6 2 9 2 4 5 8 4 0 3 4]
 [9 9 4 6 3 0 4 6 9 9 5 4 3 1 3 9]
 [9 2 9 0 7 4 3 7 6 1 0 3 7 1 2 0

In [ ]:
A = np.array(
    [[6, 3, 7, 4, 6, 9, 2, 6, 7, 4, 3, 7, 7, 2, 5, 4],
    [1, 7, 5, 1, 4, 0, 9, 5, 8, 0, 9, 2, 6, 3, 8, 2],
    [4, 2, 6, 4, 8, 6, 1, 3, 8, 1, 9, 8, 9, 4, 1, 3],
    [6, 7, 2, 0, 3, 1, 7, 3, 1, 5, 5, 9, 3, 5, 1, 9],
    [1, 9, 3, 7, 6, 8, 7, 4, 1, 4, 7, 9, 8, 8, 0, 8],
    [6, 8, 7, 0, 7, 7, 2, 0, 7, 2, 2, 0, 4, 9, 6, 9],
    [8, 6, 8, 7, 1, 0, 6, 6, 7, 4, 2, 7, 5, 2, 0, 2],
    [4, 2, 0, 4, 9, 6, 6, 8, 9, 9, 2, 6, 0, 3, 3, 4],
    [6, 6, 3, 6, 2, 5, 1, 9, 8, 4, 5, 3, 9, 6, 8, 6],
    [0, 0, 8, 8, 3, 8, 2, 6, 5, 7, 8, 4, 0, 2, 9, 7],
    [5, 7, 8, 3, 0, 0, 9, 3, 6, 1, 2, 0, 4, 0, 7, 0],
    [0, 1, 1, 5, 6, 4, 0, 0, 2, 1, 4, 9, 5, 6, 3, 6],
    [7, 0, 5, 7, 4, 3, 1, 5, 5, 0, 8, 5, 2, 3, 3, 2],
    [9, 2, 2, 3, 6, 3, 8, 0, 7, 6, 1, 7, 0, 8, 8, 1],
    [6, 9, 2, 6, 9, 8, 3, 0, 1, 0, 4, 4, 6, 8, 8, 2],
    [6, 9, 2, 6, 9, 8, 3, 0, 1, 0, 4, 4, 6, 8, 8, 2]]
)  

# T1 of r = 2
A = np.array(
[[22, 18, 22, 13],
 [13, 29, 23,  6],
 [17, 11, 22, 12],
 [23, 22, 20, 19],]
)

B = np.array(
    [[6, 3, 7, 4, 6, 9, 2, 6, 7, 4, 3, 7, 7, 2, 5, 4],
    [1, 7, 5, 1, 4, 0, 9, 5, 8, 0, 9, 2, 6, 3, 8, 2],
    [4, 2, 6, 4, 8, 6, 1, 3, 8, 1, 9, 8, 9, 4, 1, 3],
    [6, 7, 2, 0, 3, 1, 7, 3, 1, 5, 5, 9, 3, 5, 1, 9],
    [1, 9, 3, 7, 6, 8, 7, 4, 1, 4, 7, 9, 8, 8, 0, 8],
    [6, 8, 7, 0, 7, 7, 2, 0, 7, 2, 2, 0, 4, 9, 6, 9],
    [8, 6, 8, 7, 1, 0, 6, 6, 7, 4, 2, 7, 5, 2, 0, 2],
    [4, 2, 0, 4, 9, 6, 6, 8, 9, 9, 2, 6, 0, 3, 3, 4],
    [6, 6, 3, 6, 2, 5, 1, 9, 8, 4, 5, 3, 9, 6, 8, 6],
    [0, 0, 8, 8, 3, 8, 2, 6, 5, 7, 8, 4, 0, 2, 9, 7],
    [5, 7, 8, 3, 0, 0, 9, 3, 6, 1, 2, 0, 4, 0, 7, 0],
    [0, 1, 1, 5, 6, 4, 0, 0, 2, 1, 4, 9, 5, 6, 3, 6],
    [7, 0, 5, 7, 4, 3, 1, 5, 5, 0, 8, 5, 2, 3, 3, 2],
    [9, 2, 2, 3, 6, 3, 8, 0, 7, 6, 1, 7, 0, 8, 8, 1],
    [9, 2, 2, 3, 6, 3, 8, 0, 7, 6, 1, 7, 0, 8, 8, 1],
    [6, 9, 2, 6, 9, 8, 3, 0, 1, 0, 4, 4, 6, 8, 8, 2]]
)  


B = np.array(
[[22, 18, 22, 13],
 [13, 29, 23,  6],
 [11, 11, 22, 11],
 [23, 22, 20, 19],]
)


''' C
[[384 351 345 347 445 416 299 299 459 263 384 444 377 421 380 385]
 [381 322 312 314 291 217 378 298 447 220 305 356 316 295 337 199]
 [357 354 329 336 370 346 301 276 402 203 367 405 383 376 342 338]
 [288 297 298 320 339 295 294 224 347 184 299 363 299 296 347 228]
 [412 441 386 364 442 347 427 273 449 242 417 467 370 442 419 372]
 [406 386 331 314 424 381 346 238 444 215 358 381 380 437 435 281]
 [318 273 308 311 341 303 266 329 415 234 365 429 351 278 295 303]
 [317 357 304 359 371 393 318 323 400 323 320 414 321 384 365 393]
 [464 358 335 350 451 384 395 335 514 312 377 445 325 423 475 336]
 [382 362 320 296 402 358 349 231 414 285 317 397 301 402 397 348]
 [308 225 272 233 240 185 260 262 382 181 270 312 273 211 240 173]
 [249 251 177 222 280 231 230 108 212 140 228 312 219 319 253 238]
 [304 277 244 226 296 268 271 219 325 208 238 345 282 275 261 261]
 [367 289 312 326 331 332 314 253 400 289 275 444 310 370 358 308]
 [394 378 323 265 383 303 411 210 406 228 333 421 320 419 368 314]
 [394 378 323 265 383 303 411 210 406 228 333 421 320 419 368 314]]

'''


# Compute C = A . B
C = A @ B

print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)
print("\nMatrix C = A * B:")
print(C)

Matrix A:
[[6 3 7 4 6 9 2 6 7 4 3 7 7 2 5 4]
 [1 7 5 1 4 0 9 5 8 0 9 2 6 3 8 2]
 [4 2 6 4 8 6 1 3 8 1 9 8 9 4 1 3]
 [6 7 2 0 3 1 7 3 1 5 5 9 3 5 1 9]
 [1 9 3 7 6 8 7 4 1 4 7 9 8 8 0 8]
 [6 8 7 0 7 7 2 0 7 2 2 0 4 9 6 9]
 [8 6 8 7 1 0 6 6 7 4 2 7 5 2 0 2]
 [4 2 0 4 9 6 6 8 9 9 2 6 0 3 3 4]
 [6 6 3 6 2 5 1 9 8 4 5 3 9 6 8 6]
 [0 0 8 8 3 8 2 6 5 7 8 4 0 2 9 7]
 [5 7 8 3 0 0 9 3 6 1 2 0 4 0 7 0]
 [0 1 1 5 6 4 0 0 2 1 4 9 5 6 3 6]
 [7 0 5 7 4 3 1 5 5 0 8 5 2 3 3 2]
 [9 2 2 3 6 3 8 0 7 6 1 7 0 8 8 1]
 [6 9 2 6 9 8 3 0 1 0 4 4 6 8 8 2]
 [6 9 2 6 9 8 3 0 1 0 4 4 6 8 8 2]]

Matrix B:
[[6 3 7 4 6 9 2 6 7 4 3 7 7 2 5 4]
 [1 7 5 1 4 0 9 5 8 0 9 2 6 3 8 2]
 [4 2 6 4 8 6 1 3 8 1 9 8 9 4 1 3]
 [6 7 2 0 3 1 7 3 1 5 5 9 3 5 1 9]
 [1 9 3 7 6 8 7 4 1 4 7 9 8 8 0 8]
 [6 8 7 0 7 7 2 0 7 2 2 0 4 9 6 9]
 [8 6 8 7 1 0 6 6 7 4 2 7 5 2 0 2]
 [4 2 0 4 9 6 6 8 9 9 2 6 0 3 3 4]
 [6 6 3 6 2 5 1 9 8 4 5 3 9 6 8 6]
 [0 0 8 8 3 8 2 6 5 7 8 4 0 2 9 7]
 [5 7 8 3 0 0 9 3 6 1 2 0 4 0 7 0]
 [0 1 1 5 6 4 0 0 2 1 4 9 5 6 3 6

In [ ]:
# Define vectors
v1 = np.array([1, 2, 3]) 
v2 = np.array([4, 5, 6])  

# Compute addition and subtraction
v_add = v1 + v2
v_sub = v1 - v2

print("Vector 1:", v1)
print("Vector 2:", v2)
print("\nVector Addition (v1 + v2):", v_add)
print("\nVector Subtraction (v1 - v2):", v_sub)


In [ ]:
def split_matrix(A):
    """Splits a matrix into four quadrants."""
    n = A.shape[0] // 2
    return A[:n, :n], A[:n, n:], A[n:, :n], A[n:, n:]

# Define matrices A and B
A = np.array(
    [[6, 3, 7, 4, 6, 9, 2, 6, 7, 4, 3, 7, 7, 2, 5, 4],
    [1, 7, 5, 1, 4, 0, 9, 5, 8, 0, 9, 2, 6, 3, 8, 2],
    [4, 2, 6, 4, 8, 6, 1, 3, 8, 1, 9, 8, 9, 4, 1, 3],
    [6, 7, 2, 0, 3, 1, 7, 3, 1, 5, 5, 9, 3, 5, 1, 9],
    [1, 9, 3, 7, 6, 8, 7, 4, 1, 4, 7, 9, 8, 8, 0, 8],
    [6, 8, 7, 0, 7, 7, 2, 0, 7, 2, 2, 0, 4, 9, 6, 9],
    [8, 6, 8, 7, 1, 0, 6, 6, 7, 4, 2, 7, 5, 2, 0, 2],
    [4, 2, 0, 4, 9, 6, 6, 8, 9, 9, 2, 6, 0, 3, 3, 4],
    [6, 6, 3, 6, 2, 5, 1, 9, 8, 4, 5, 3, 9, 6, 8, 6],
    [0, 0, 8, 8, 3, 8, 2, 6, 5, 7, 8, 4, 0, 2, 9, 7],
    [5, 7, 8, 3, 0, 0, 9, 3, 6, 1, 2, 0, 4, 0, 7, 0],
    [0, 1, 1, 5, 6, 4, 0, 0, 2, 1, 4, 9, 5, 6, 3, 6],
    [7, 0, 5, 7, 4, 3, 1, 5, 5, 0, 8, 5, 2, 3, 3, 2],
    [9, 2, 2, 3, 6, 3, 8, 0, 7, 6, 1, 7, 0, 8, 8, 1],
    [6, 9, 2, 6, 9, 8, 3, 0, 1, 0, 4, 4, 6, 8, 8, 2],
    [6, 9, 2, 6, 9, 8, 3, 0, 1, 0, 4, 4, 6, 8, 8, 2]]
)  


# T1 of r=1
A = np.array(
    [[14,  7 ,12 , 7 ,15 ,15 ,10 ,12],
    [ 6, 14 ,13 , 5 , 4 , 2 ,18 ,12],
    [10,  3 , 8 , 4 ,12 , 6 , 8 , 3],
    [ 8,  8 , 6 , 9 , 8 , 7 ,10 , 9],
    [ 6,  9 ,11 ,12 , 8 ,11 ,10 , 6],
    [13, 14 , 8 , 7 , 7 ,15 ,10 , 1],
    [ 9,  6 ,12 ,11 , 7 , 8 ,14 , 8],
    [ 5,  2 , 4 , 8 ,15 ,14 ,14 ,10]],
)

# T1 of r = 2
A = np.array(
[[22, 18, 22, 13],
 [13, 29, 23,  6],
 [17, 11, 22, 12],
 [23, 22, 20, 19],]
)


B = np.array(
    [[6, 3, 7, 4, 6, 9, 2, 6, 7, 4, 3, 7, 7, 2, 5, 4],
    [1, 7, 5, 1, 4, 0, 9, 5, 8, 0, 9, 2, 6, 3, 8, 2],
    [4, 2, 6, 4, 8, 6, 1, 3, 8, 1, 9, 8, 9, 4, 1, 3],
    [6, 7, 2, 0, 3, 1, 7, 3, 1, 5, 5, 9, 3, 5, 1, 9],
    [1, 9, 3, 7, 6, 8, 7, 4, 1, 4, 7, 9, 8, 8, 0, 8],
    [6, 8, 7, 0, 7, 7, 2, 0, 7, 2, 2, 0, 4, 9, 6, 9],
    [8, 6, 8, 7, 1, 0, 6, 6, 7, 4, 2, 7, 5, 2, 0, 2],
    [4, 2, 0, 4, 9, 6, 6, 8, 9, 9, 2, 6, 0, 3, 3, 4],
    [6, 6, 3, 6, 2, 5, 1, 9, 8, 4, 5, 3, 9, 6, 8, 6],
    [0, 0, 8, 8, 3, 8, 2, 6, 5, 7, 8, 4, 0, 2, 9, 7],
    [5, 7, 8, 3, 0, 0, 9, 3, 6, 1, 2, 0, 4, 0, 7, 0],
    [0, 1, 1, 5, 6, 4, 0, 0, 2, 1, 4, 9, 5, 6, 3, 6],
    [7, 0, 5, 7, 4, 3, 1, 5, 5, 0, 8, 5, 2, 3, 3, 2],
    [9, 2, 2, 3, 6, 3, 8, 0, 7, 6, 1, 7, 0, 8, 8, 1],
    [9, 2, 2, 3, 6, 3, 8, 0, 7, 6, 1, 7, 0, 8, 8, 1],
    [6, 9, 2, 6, 9, 8, 3, 0, 1, 0, 4, 4, 6, 8, 8, 2]]
)  

# S1 of r = 1
B = np.array(
    [[14,  7, 12 , 7 ,15, 15, 10, 12,],
    [ 6 , 14, 13 , 5 , 4,  2, 18, 12,],
    [10 ,  3,  8 , 4 ,12,  6,  8,  3,],
    [ 8 ,  8,  6 , 9 , 8,  7, 10,  9,],
    [ 6 ,  9, 11 ,12 , 8, 11, 10,  6,],
    [13 , 14,  8 , 7 , 7, 15, 10,  1,],
    [15 , 12,  9 ,14 , 1,  8, 14,  7,],
    [ 5 ,  2,  4 , 8 ,15, 14, 14, 10,],]
)


# S1 of r = 2
B = np.array(
[[22, 18, 22, 13],
 [13, 29, 23,  6],
 [11, 11, 22, 11],
 [23, 22, 20, 19],]
)



# Split into quadrants
A11, A12, A21, A22 = split_matrix(A)
B11, B12, B21, B22 = split_matrix(B)

# Compute T-matrices
T1 = A11 + A22
T2 = A21 + A22
T3 = A11
T4 = A22
T5 = A11 + A12
T6 = A21 - A11
T7 = A12 - A22

# Compute S-matrices
S1 = B11 + B22
S2 = B11
S3 = B12 - B22
S4 = B21 - B11
S5 = B22
S6 = B11 + B12
S7 = B21 + B22

# Print matrices
print("T-matrices:")
for i, T in enumerate([T1, T2, T3, T4, T5, T6, T7], 1):
    print(f"T{i}:\n{T}\n")

print("S-matrices:")
for i, S in enumerate([S1, S2, S3, S4, S5, S6, S7], 1):
    print(f"S{i}:\n{S}\n")


T-matrices:
T1:
[[22 18 22 13]
 [13 29 23  6]
 [17 11 22 12]
 [23 22 20 19]]

T2:
[[14 20 21 18]
 [20 29 18  8]
 [16 14 26 19]
 [20 16 18 18]]

T3:
[[14  7 12  7]
 [ 6 14 13  5]
 [10  3  8  4]
 [ 8  8  6  9]]

T4:
[[ 8 11 10  6]
 [ 7 15 10  1]
 [ 7  8 14  8]
 [15 14 14 10]]

T5:
[[29 22 22 19]
 [10 16 31 17]
 [22  9 16  7]
 [16 15 16 18]]

T6:
[[-8  2 -1  5]
 [ 7  0 -5  2]
 [-1  3  4  7]
 [-3 -6 -2 -1]]

T7:
[[  7   4   0   6]
 [ -3 -13   8  11]
 [  5  -2  -6  -5]
 [ -7  -7  -4  -1]]

S-matrices:
S1:
[[22 18 22 13]
 [13 29 23  6]
 [11 11 22 11]
 [23 22 20 19]]

S2:
[[14  7 12  7]
 [ 6 14 13  5]
 [10  3  8  4]
 [ 8  8  6  9]]

S3:
[[  7   4   0   6]
 [ -3 -13   8  11]
 [ 11  -2  -6  -4]
 [ -7  -7  -4  -1]]

S4:
[[-8  2 -1  5]
 [ 7  0 -5  2]
 [ 5  9  1 10]
 [-3 -6 -2 -1]]

S5:
[[ 8 11 10  6]
 [ 7 15 10  1]
 [ 1  8 14  7]
 [15 14 14 10]]

S6:
[[29 22 22 19]
 [10 16 31 17]
 [22  9 16  7]
 [16 15 16 18]]

S7:
[[14 20 21 18]
 [20 29 18  8]
 [16 20 23 21]
 [20 16 18 18]]

